// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABhPDC4X6Sq20RJL9kur1b8FWwN0NZSw',
    appId: '1:806787763701:web:97d1bdd16abb30df9664bc',
    messagingSenderId: '806787763701',
    projectId: 'appflowy-theme-marketpla-e8f9b',
    authDomain: 'appflowy-theme-marketpla-e8f9b.firebaseapp.com',
    storageBucket: 'appflowy-theme-marketpla-e8f9b.appspot.com',
    measurementId: 'G-NXP4DZ43R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0hcWFhkmFgv9gP-ogjVgp8LhNvsizyc',
    appId: '1:806787763701:android:f76512fc89190c049664bc',
    messagingSenderId: '806787763701',
    projectId: 'appflowy-theme-marketpla-e8f9b',
    storageBucket: 'appflowy-theme-marketpla-e8f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI77BNBYn4xhi6jlz0oNimd5IPz6mgye4',
    appId: '1:806787763701:ios:6519fad4c098674b9664bc',
    messagingSenderId: '806787763701',
    projectId: 'appflowy-theme-marketpla-e8f9b',
    storageBucket: 'appflowy-theme-marketpla-e8f9b.appspot.com',
    iosClientId: '806787763701-en62uhjnm7lr09j09u49lg9d70hfkl6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.appflowyThemeMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI77BNBYn4xhi6jlz0oNimd5IPz6mgye4',
    appId: '1:806787763701:ios:6519fad4c098674b9664bc',
    messagingSenderId: '806787763701',
    projectId: 'appflowy-theme-marketpla-e8f9b',
    storageBucket: 'appflowy-theme-marketpla-e8f9b.appspot.com',
    iosClientId: '806787763701-en62uhjnm7lr09j09u49lg9d70hfkl6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.appflowyThemeMarketplace',
  );
}
